name: Release it
description: Release it Composite Github Action

inputs:
  release-branch:
    description: Which branch you would like to release
    default: main
  dry-run:
    description: "Dry run"
    required: false
    default: "false"
  no-npm:
    description: "Skip releasing it to npm"
    required: false
    default: "false"
  no-git:
    description: "Skip releasing it to Github"
    required: false
    default: "false"
  manual-version:
    description: "Sets explicit version for the release. For example: 1.0.0"
    required: false
  git-user:
    description: "Github username"
    required: true
  git-email:
    description: "Github email"
    required: true
  git-token:
    description: "Github token to push release"
    required: true

outputs:
  version:
    description: "Version of successful release"
    value: ${{ steps.release-it.outputs.version }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v4.1.0
      with:
        node-version: lts/*

    - name: Init Git user
      shell: bash
      run: |
        git config --global user.email "${{ inputs.git-user }}"
        git config --global user.name "${{ inputs.git-user }}"

    - name: Release
      shell: bash
      id: release-it
      env:
        GITHUB_TOKEN: ${{ inputs.git-token }}
      run: |
        dry_run=""
        pre_release=""
        no_npm=""
        manual_version=""
        no_git=""

        if [ "${{ inputs.dry-run }}" == "true" ]; then dry_run="--dry-run"; fi
        if [ "${{ inputs.release-branch }}" != "main" ]; then pre_release="--preRelease=${{ inputs.release-branch }}"; fi
        if [ "${{ inputs.no-npm }}" == "true" ]; then no_npm="--no-npm"; fi
        if [ "${{ inputs.manual-version }}" != "" ]; then manual_version="\"${{ inputs.manual-version }}\""; fi
        if [ "${{ inputs.no-git }}" == "true" ]; then no_git="--no-git"; fi

        npx release-it $manual_version --ci $pre_release $dry_run $no_npm $no_git
