name: Release
on:
  workflow_dispatch:
    inputs:
      release-branch:
        type: choice
        description: To which branch you want to release
        default: main
        options:
          - main
          - beta
          - rc
      dry-run:
        type: boolean
        description: "Dry run"
        required: true
        default: true
      no-npm:
        type: boolean
        description: "Skip push to npm"
        required: true
        default: false

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: ./
